update_films_data: Обновление видеотеки Smarty
microimpuls/smarty-api-lib pull request #22
Opened 2023-09-04 11:30 UTC by BergaBruh

* Добавлена информация о скрипте
* Добавлен скрипт на обновление видеотеки (требуется `kinopoisk_id` в Smarty)

2023-09-05 08:18 UTC, ArthurO-micimp requested changes
Можно переделать по аналогии с sync_content, сделать отдельный класс, которому при инициализации надо передать api.

А еще не хватает тайпхинтов в функциях.

2023-09-05 08:18 UTC, ArthurO-micimp commented on content-api/python/update_films_data.py
> +def get_from_smarty_films_in_the_form_json_list(page):
Функция, название которой начинается на get должна что-то возвращать, поэтому надо переименовать.

2023-09-05 08:18 UTC, ArthurO-micimp commented on content-api/python/update_films_data.py
> +    limit_film = 100 # Количество фильмов/Сериалов на одну страницу
Это можно вынести в объявление функции.

2023-09-05 08:18 UTC, ArthurO-micimp commented on content-api/python/update_films_data.py
> +    get_api_response = api.video_list(limit=limit_film, page=page)
api берется из глобального пространства - так делать не стоит. Надо вынести api в объявление функции.

2023-09-05 08:18 UTC, ArthurO-micimp commented on content-api/python/update_films_data.py
> +def get_from_smarty_films_data(videos_info, video_count, number, page, limit_film):
Аналогично, название функции не совсем отражает то, что она делает.

2023-09-05 08:18 UTC, ArthurO-micimp commented on content-api/python/update_films_data.py
> +    while video_count > page:
Сравнение количества видео с номером страницы не выглядит корректно. Либо тут логическая ошибка, либо неправильное название для переменных.

2023-09-05 08:18 UTC, ArthurO-micimp commented on content-api/python/update_films_data.py
> +                    f"API и добавлена в Smarty.")
Лучше просто написать что была загружена метаинформация. Метаинформация может подтягиваться и из других источников тоже.

2023-09-05 08:18 UTC, ArthurO-micimp commented on content-api/python/update_films_data.py
> +                get_from_smarty_films_in_the_form_json_list(page)
Рекурсию лучше избегать, у нее есть свойство занимать весь стэк и заканчивать на этом выполнение.
Лучше всего в данном случае было бы сделать обновление данных через цикл. Для этого надо сначала сделать запрос video_list с параметром limit=0, чтобы получить сколько всего фильмов. После этого циклом через каждые N фильмов получать их и обновлять:
```
response = api.video_list(limit=0,page=1)
count = response['count']
limit = 100
for i in range(1, int(count/limit)):
    response = api.video_list(limit=limit,page=i)
    videos = response['videos']
    update_videos(api, videos)
```

2023-09-06 05:36 UTC, BergaBruh commented
Скрипт был переписан по аналогии с sync_content. Требуется перепроверка кода.

2023-09-06 07:29 UTC, ArthurO-micimp requested changes

2023-09-06 07:29 UTC, ArthurO-micimp commented on content-api/python/update_films_data.py
> +            ParseError()
Чтобы бросить исключение, надо писать `raise ParseError`. Да и название у исключения некорректное - исключение возникает из-за подключения, а не парсинга. Впрочем, здесь вообще нет смысла делать отдельное исключение, так как обрабатывать каждое исключение в данном случае довольно трудно, поэтому при первой же ошибке достаточно вывести ошибку и прекратить выполнение.

2023-09-06 07:29 UTC, ArthurO-micimp commented on content-api/python/update_films_data.py
> +            except ContentAPIException as error:
Здесь отловится только одна ошибка: ContentAPIException, все остальные вывалятся во внешку и, скорее всего, не будут обработаны. В данном случае можно ловить вообще все исключения: `except Exception as e:`

2023-09-06 07:29 UTC, ArthurO-micimp commented on content-api/python/update_films_data.py
> +    def load_data(self):
Можно назвать метод `run`, тогда будет понятно, что он запустит процесс обновления данных.

2023-09-06 07:29 UTC, ArthurO-micimp commented on content-api/python/update_films_data.py
> +    def __init__(self, api, videos_per_page):
Вот тут точно стоит добавить тайпхинты, так как этот класс, по идее, вызывается сторонними разработчиками, поэтому им будет лучше, если они будут знать какие типы нужно передавать в аргументы:
`api: SmartyContentAPI`
videos_per_page сам по себе к классу не относится, его можно вынести в `run(videos_per_page: int)`

2023-09-06 09:53 UTC, BergaBruh commented
Скрипт был подправлен в некоторых местах. Требуется перепроверка кода.

2023-09-06 10:03 UTC, ArthurO-micimp requested changes
Небольшие фиксы внести и всё ок.

2023-09-06 10:03 UTC, ArthurO-micimp commented on content-api/python/update_films_data.py
> +        return pages+1
Всё таки тут я был не прав, +1 действительно должно быть внутри range для того чтобы последнюю страницу включать в список.

2023-09-06 10:03 UTC, ArthurO-micimp commented on content-api/python/update_films_data.py
> +            pages (:obj:`int`): Номер страницы.
Всё нормально, только вот эту часть надо убрать. Аргументов у метода run нет, поэтому и описывать их не надо.

2023-09-06 10:13 UTC, BergaBruh commented
Сделал последние исправления.

2023-09-07 13:25 UTC, merged